### ISSUE TITLE
how to get CONCEPT.csv

### ISSUE THREAD

**Issue by leipzig** [jasonbaik94/clinical_trials#1]
hi can you point me to your RxNorm vocab file?
`vocabulary_download_v5_{d62de2e4-9825-4917-8ccb-d92395a5778e}_1535207123450/CONCEPT.csv`

**Comment by ngiangre** [comment]
Hi Jeremy,

Sure thing! Actually, you can download your own version on your machine instead of me transferring a could hundred MBs. It'll work just fine, but if it doesn't let me know and I can share with you.

If you go to http://athena.ohdsi.org/search-terms/terms,

then click the downloads tab in the upper right side of the page,

deselect all the tables, on the upper left side of the page, and then select SNOMED and RxNorm tables,

Click the download vocabularies tab in the upper right side of the page,

Then click download again (you can name the zip file that's downloaded with the tables), and then it'll notify you via email when they are ready and the link where they can be downloaded.

In the scripts/notebooks you would just need to change the file paths and names per your local copies. 

If that doesn't work, I can share with you the files via gdrive or something (I didn't have them up on github initially because they're too large). 

Hope this helps!

**Comment by leipzig** [comment]
yes thanks for this walkthrough. very helpful!
